## Exploratory Data Analysis of Master Dataset - Merged Fake and True (Combined Counts)
---

### Import Relevant Libraries

In [13]:
# For dataset manipulation
import numpy as np
import pandas as pd
# For punctuation count
import spacy
# For readability ease count
import textstat
# For progress bar
from tqdm.notebook import tqdm
tqdm.pandas()

### Merge the Datasets into Master Dataset

In [14]:
# Store the datasets into variables
df_fake = pd.read_csv("../../Datasets/Dataset1_fake_combined_counts_cleaned_1.csv")
df_true = pd.read_csv("../../Datasets/Dataset1_true_combined_counts_cleaned_1.csv")

In [15]:
df_all = pd.concat([df_fake, df_true], ignore_index=True)
df_all

,combined_data,combined_word_count,combined_punct_count,combined_readability_ease,label
0,Donald Trump Sends Out Embarrassing New Year’...,507,102,62.27,0
1,Drunk Bragging Trump Staffer Started Russian ...,313,34,45.35,0
2,Sheriff David Clarke Becomes An Internet Joke...,595,105,63.19,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,458,68,53.00,0
4,Pope Francis Just Called Out Donald Trump Dur...,431,40,58.01,0
...,...,...,...,...,...
39100,'Fully committed' NATO backs new U.S. approach...,475,51,51.68,1
39101,LexisNexis withdrew two products from Chinese ...,132,18,32.43,1
39102,Minsk cultural hub becomes haven from authorit...,327,48,50.87,1
39103,Vatican upbeat on possibility of Pope Francis ...,214,20,47.42,1
39104,Indonesia to buy $1.14 billion worth of Russia...,219,22,36.18,1

In [16]:
df_all["label"].value_counts()

label
1    21197
0    17908
Name: count, dtype: int64

### Shuffle the Order of the Dataset

In [17]:
df_all = df_all.sample(frac=1, random_state=42).reset_index(drop=True)
df_all

,combined_data,combined_word_count,combined_punct_count,combined_readability_ease,label
0,Many 'lost' voters say they have found their c...,1101,184,50.06,1
1,"Iranian Revolutionary Guards commander, anothe...",409,50,28.77,1
2,Cambodian leader gets China's backing as West ...,602,58,48.13,1
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,442,52,61.97,0
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,29,4,25.12,0
...,...,...,...,...,...
39100,Hillary’s Message To Former Miss Universe Cal...,260,39,63.39,0
39101,SENIOR CIA INTEL: “Wiretapping of Trump Transi...,12,5,17.00,0
39102,Ex-Georgian leader Saakashvili barges across U...,507,61,49.35,1
39103,Trump Stole An Idea From North Korean Propaga...,887,160,69.72,0
39104,WATCH JUDGE TELL DISRESPECTFUL GANGBANGER Taxp...,817,86,72.46,0

### Save the Updated Dataset

In [18]:
df_all.to_csv("../../Datasets/Dataset1_master_combined_counts_cleaned_1.csv")