## Exploratory Data Analysis of Master Dataset - Merged Fake and True (Title and Text Counts)
---

### Import Relevant Libraries

In [1]:
# For dataset manipulation
import numpy as np
import pandas as pd
# For punctuation count
import spacy
# For readability ease count
import textstat
# For progress bar
from tqdm.notebook import tqdm
tqdm.pandas()

### Merge the Datasets into Master Dataset

In [3]:
# Store the datasets into variables
df_fake = pd.read_csv("../../Datasets/Dataset1_fake_counts_cleaned_1.csv")
df_true = pd.read_csv("../../Datasets/Dataset1_true_counts_cleaned_1.csv")

In [6]:
df_all = pd.concat([df_fake, df_true], ignore_index=True)
df_all

,title,title_word_count,title_punct_count,title_readability_ease,text,text_word_count,text_punct_count,text_readability_ease,label
0,Donald Trump Sends Out Embarrassing New Year’...,12,1,59.30,Donald Trump just couldn t wish all Americans ...,495,101,62.68,0
1,Drunk Bragging Trump Staffer Started Russian ...,8,0,4.14,House Intelligence Committee Chairman Devin Nu...,305,34,45.86,0
2,Sheriff David Clarke Becomes An Internet Joke...,15,2,64.71,"On Friday, it was revealed that former Milwauk...",580,103,63.59,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,14,2,57.27,"On Christmas day, Donald Trump announced that ...",444,66,53.61,0
4,Pope Francis Just Called Out Donald Trump Dur...,11,0,77.23,Pope Francis used his annual Christmas Day mes...,420,40,58.62,0
...,...,...,...,...,...,...,...,...,...
39100,'Fully committed' NATO backs new U.S. approach...,9,2,41.53,BRUSSELS (Reuters) - NATO allies on Tuesday we...,466,49,51.28,1
39101,LexisNexis withdrew two products from Chinese ...,7,0,30.53,"LONDON (Reuters) - LexisNexis, a provider of l...",125,18,33.54,1
39102,Minsk cultural hub becomes haven from authorities,7,0,30.53,MINSK (Reuters) - In the shadow of disused Sov...,320,48,51.28,1
39103,Vatican upbeat on possibility of Pope Francis ...,9,0,11.58,MOSCOW (Reuters) - Vatican Secretary of State ...,205,20,56.89,1
39104,Indonesia to buy $1.14 billion worth of Russia...,9,0,66.91,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,210,22,35.37,1

### Shuffle the Order of the Dataset

In [7]:
df_all = df_all.sample(frac=1, random_state=42).reset_index(drop=True)
df_all

,title,title_word_count,title_punct_count,title_readability_ease,text,text_word_count,text_punct_count,text_readability_ease,label
0,Many 'lost' voters say they have found their c...,11,2,77.23,WASHINGTON/NEW YORK (Reuters) - Ted Wade hasn’...,1090,182,50.26,1
1,"Iranian Revolutionary Guards commander, anothe...",11,3,-41.22,BEIRUT (Reuters) - A commander in Iran s elite...,398,47,37.84,1
2,Cambodian leader gets China's backing as West ...,9,0,36.96,PHNOM PENH (Reuters) - Cambodian Prime Ministe...,593,58,48.43,1
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,15,4,89.24,David Duke is perhaps one of the most notoriou...,427,48,61.87,0
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,13,3,15.98,Hillary Clinton shows her true colors here wit...,16,1,63.70,0
...,...,...,...,...,...,...,...,...,...
39100,Hillary’s Message To Former Miss Universe Cal...,14,4,74.19,Miss Universe 1996 Alicia Machado is now an Am...,246,35,64.30,0
39101,SENIOR CIA INTEL: “Wiretapping of Trump Transi...,12,5,17.00,,0,0,206.84,0
39102,Ex-Georgian leader Saakashvili barges across U...,7,1,22.07,"SHEHYNI, Ukraine (Reuters) - Former Georgian p...",500,60,49.65,1
39103,Trump Stole An Idea From North Korean Propaga...,16,2,38.32,Jesus f*cking Christ our President* is a moron...,871,158,70.02,0
39104,WATCH JUDGE TELL DISRESPECTFUL GANGBANGER Taxp...,16,3,55.24,Maybe if we had more people in positions of au...,801,83,72.46,0

In [8]:
df_all["label"].value_counts()

label
1    21197
0    17908
Name: count, dtype: int64

### Save the Updated Dataset

In [9]:
df_all.to_csv("../../Datasets/Dataset1_master_counts_cleaned_1.csv")