## Exploratory Data Analysis of Master Dataset - Datasets 1 and 2

### Import the relevant libraries

In [54]:
# For dataset manipulation
import pandas as pd

### Merge the datasets into a master dataset

In [55]:
# Store the datasets into variables
df_fake = pd.read_csv("../../../Datasets/Dataset1_fake_counts.csv")
df_true = pd.read_csv("../../../Datasets/Dataset1_true_counts.csv")
df_mixed = pd.read_csv("../../../Datasets/Dataset2_mixed_counts.csv")

In [56]:
df_all = pd.concat([df_fake, df_true, df_mixed], ignore_index=True)

In [57]:
# Show the master dataset
df_all

,title,title_word_count,title_punct_count,title_readability_ease,text,text_word_count,text_punct_count,text_readability_ease,label
0,Donald Trump Sends Out Embarrassing New Year’...,12,1,59.30,Donald Trump just couldn t wish all Americans ...,495,101,62.68,0
1,Drunk Bragging Trump Staffer Started Russian ...,8,0,4.14,House Intelligence Committee Chairman Devin Nu...,305,34,45.86,0
2,Sheriff David Clarke Becomes An Internet Joke...,15,2,64.71,"On Friday, it was revealed that former Milwauk...",580,103,63.59,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,14,2,57.27,"On Christmas day, Donald Trump announced that ...",444,66,53.61,0
4,Pope Francis Just Called Out Donald Trump Dur...,11,0,77.23,Pope Francis used his annual Christmas Day mes...,420,40,58.62,0
...,...,...,...,...,...,...,...,...,...
117027,Russians steal research on Trump in hack of U....,11,0,68.77,WASHINGTON (Reuters) - Hackers believed to be ...,735,103,42.92,0
117028,WATCH: Giuliani Demands That Democrats Apolog...,10,1,27.49,"You know, because in fantasyland Republicans n...",604,48,49.55,1
117029,Migrants Refuse To Leave Train At Refugee Camp...,10,0,61.33,Migrants Refuse To Leave Train At Refugee Camp...,477,74,50.46,0
117030,Trump tussle gives unpopular Mexican leader mu...,10,1,35.95,MEXICO CITY (Reuters) - Donald Trump’s combati...,559,83,47.93,0
117031,Goldman Sachs Endorses Hillary Clinton For Pre...,7,0,22.07,Goldman Sachs Endorses Hillary Clinton For Pre...,448,71,59.43,1

### Save the master dataset

In [58]:
df_all.to_csv('../../../Datasets/Dataset_master_counts.csv', index=False)

### Combining Title + Text

In [59]:
df_all = df_all.drop(columns=[
    'title_word_count', 
    'title_punct_count',
    'title_readability_ease',
    'text_word_count', 
    'text_punct_count',
    'text_readability_ease'
]).reset_index(drop=True)

In [60]:
df_all['combined_data'] = df_all['title'] + ' ' + df_all['text']

In [61]:
df_all = df_all[["title", "text", "combined_data", "label"]]

In [62]:
df_all

,title,text,combined_data,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,Donald Trump Sends Out Embarrassing New Year’...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,Drunk Bragging Trump Staffer Started Russian ...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",Sheriff David Clarke Becomes An Internet Joke...,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",Trump Is So Obsessed He Even Has Obama’s Name...,0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,Pope Francis Just Called Out Donald Trump Dur...,0
...,...,...,...,...
117027,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,Russians steal research on Trump in hack of U....,0
117028,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",WATCH: Giuliani Demands That Democrats Apolog...,1
117029,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
117030,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,Trump tussle gives unpopular Mexican leader mu...,0
117031,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

### Save the Updated Dataset

In [63]:
df_all.to_csv('../../../Datasets/Dataset_master_combineddata.csv', index=False)